image: docker:git

services:
- docker:dind

stages:
- build
- test
- release

variables:
  TEST_IMAGE: briar/tor-reproducer:${CI_BUILD_REF_NAME}
  RELEASE_IMAGE: briar/tor-reproducer:latest

before_script:
  - echo ${DOCKER_HUB_PASS} | docker login -u ${DOCKER_HUB_USER} --password-stdin

build:
  stage: build
  script:
    - docker build -t ${TEST_IMAGE} .
    - docker push $TEST_IMAGE

test_build:
  stage: test
  script:
    - docker run ${TEST_IMAGE} /bin/bash -c "./build-tor.py && ./verify-tor.py"
  artifacts:
    paths:
    - tor-*.zip
    - tor-*.pom
    - tor-*-sources.jar
    expire_in: 1 week
  allow_failure: true
  except:
    - tags

test_tag:
  stage: test
  script:
    - docker run ${TEST_IMAGE} ./verify-tor.py ${CI_BUILD_REF_NAME}
  artifacts:
    paths:
    - tor-*.zip
    - tor-*.pom
    - tor-*-sources.jar
    expire_in: 1 week
  only:
    - tags

release:
  stage: release
  script:
    - docker pull $TEST_IMAGE
    - docker tag $TEST_IMAGE $RELEASE_IMAGE
    - docker push $RELEASE_IMAGE
  when: on_success
  only:
    - master
