image: docker:git

services:
- docker:dind

stages:
- build
- test
- release

variables:
  TEST_IMAGE: briar/tor-reproducer:${CI_BUILD_REF_NAME}
  RELEASE_IMAGE: briar/tor-reproducer:latest

before_script:
  - echo ${DOCKER_HUB_PASS} | docker login -u ${DOCKER_HUB_USER} --password-stdin

build:
  stage: build
  script:
    - docker build -t ${TEST_IMAGE} .
    - docker push $TEST_IMAGE

.base-test:
  stage: test
  artifacts:
    paths:
      - output/*/tor-*.jar
      - output/*/tor-*.pom
    expire_in: 1 week
    when: always

test_build_android:
  extends: .base-test
  script:
    - docker run -v `pwd`/output:/opt/tor-reproducer/output ${TEST_IMAGE} /bin/bash -c "./build_tor_android.py && ./verify_tor_android.py"
  allow_failure: true
  except:
    - tags

test_build_linux:
  extends: .base-test
  script:
    - docker run -v `pwd`/output:/opt/tor-reproducer/output ${TEST_IMAGE} /bin/bash -c "./build_tor_linux.py && ./verify_tor_linux.py"
  allow_failure: true
  except:
    - tags

test_build_windows:
  extends: .base-test
  script:
    - docker run -v `pwd`/output:/opt/tor-reproducer/output ${TEST_IMAGE} /bin/bash -c "./build_tor_windows.py && ./verify_tor_windows.py"
  allow_failure: true
  except:
    - tags

test_tag_android:
  extends: .base-test
  script:
    - docker run -v `pwd`/output:/opt/tor-reproducer/output ${TEST_IMAGE} ./verify_tor.py ${CI_BUILD_REF_NAME}
  only:
    - tags

test_tag_linux:
  extends: .base-test
  script:
    - docker run -v `pwd`/output:/opt/tor-reproducer/output ${TEST_IMAGE} ./verify_tor_linux.py ${CI_BUILD_REF_NAME}
  only:
    - tags

test_tag_windows:
  extends: .base-test
  script:
    - docker run -v `pwd`/output:/opt/tor-reproducer/output ${TEST_IMAGE} ./verify_tor_windows.py ${CI_BUILD_REF_NAME}
  only:
    - tags

release:
  stage: release
  script:
    - docker pull $TEST_IMAGE
    - docker tag $TEST_IMAGE $RELEASE_IMAGE
    - docker push $RELEASE_IMAGE
  when: on_success
  only:
    - master
