image: docker:git

services:
- docker:dind

stages:
- build
- test
- release

variables:
  TEST_IMAGE: briar/tor-reproducer:${CI_BUILD_REF_NAME}
  RELEASE_IMAGE: briar/tor-reproducer:latest

before_script:
  - echo ${DOCKER_HUB_PASS} | docker login -u ${DOCKER_HUB_USER} --password-stdin

build:
  stage: build
  script:
    - docker build -t ${TEST_IMAGE} .
    - docker push $TEST_IMAGE

# TODO unify with test_verify once latest stable release was uploaded to jcenter
test_build:
  stage: test
  script:
    - docker run ${TEST_IMAGE} ./build-tor.py
  except:
    - tags

test_verify:
  stage: test
  script:
    - docker run ${TEST_IMAGE} ./verify-tor.py ${CI_BUILD_REF_NAME}
  only:
    - tags

release:
  stage: release
  script:
    - docker pull $TEST_IMAGE
    - docker tag $TEST_IMAGE $RELEASE_IMAGE
    - docker push $RELEASE_IMAGE
  only:
    - master
